steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - run
      - -d
      - --network=cloudbuild
      - --name=firebase-runner
      - europe-west2-docker.pkg.dev/pyruby-web-home/pyruby-web-home/firebase-builder:0.1
      - emulators:start
      - --project=$PROJECT_ID
    id: start firebase
  - name: europe-west2-docker.pkg.dev/pyruby-web-home/pyruby-web-home/python-builder:0.7
    args:
      - wait-for-it
      - firebase-runner:9099
      - -s
      - --timeout=60
      - --
      - make
      - ci
    env:
      - FIRESTORE_EMULATOR_HOST=firebase-runner:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-runner:9099
    id: run CI checks
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GAR_HOSTNAME/$_ARTIFACT_REPO/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'
    id: Build deployable
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GAR_HOSTNAME/$_ARTIFACT_REPO/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push docker image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GAR_HOSTNAME/$_ARTIFACT_REPO/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy to cloud run
    entrypoint: gcloud
images:
  - '$_GAR_HOSTNAME/$_ARTIFACT_REPO/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _LABELS: service-manager=pyruby
  _SERVICE_NAME: pyruby-backend
  _DEPLOY_REGION: europe-west2
  _GAR_HOSTNAME: europe-west2-docker.pkg.dev
  _ARTIFACT_REPO: pyruby-web-home/pyruby-web-home
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - pyruby-backend
